export const css: string;
export const contents: string;
export const horizontal: string;
export const scrollbar: string;
export const variablesScrollbarScrollSize: string;
export const variablesScrollbarThickness: string;
export const variablesScrollbarThumb: string;
export const variablesScrollbarTrack: string;
export const vertical: string;